version: "2"
services:
    nginx-cache:
        image: quay.io/alayacare/nginx-cache:latest
        environment:
            BACKEND: https://server.example.com
            INACTIVE: 15m
            MAX_SIZE: 20m
        tmpfs:
        - /tmp/nginx/cache
