version: "2"
services:
    nginx-cache:
        image: quay.io/alayacare/nginx-cache:latest
        environment:
            BACKEND: server.example.com:443
            #BACKENDS: b1.example.com:443 b2.example.com:443
            #INACTIVE: 5m
            #MAX_SIZE: 20m
        tmpfs:
        - /tmp/nginx/cache
        - /var/cache/nginx/proxy_temp

